mode: "dev"  # "dev" or "production"

server:
  http:
    enabled: true
    bind_address: "0.0.0.0"
    port: 8085
  tls:
    enabled: false
    bind_address: "0.0.0.0"
    port: 8086
    cert:   "/etc/letsencrypt/live/xxxx/fullchain.pem"
    key:    "/etc/letsencrypt/live/xxxx/privkey.pem"

upload:
  path:            "./uploads"
  max_size:        5000000000 # 5GiB   
  max_per_hour:    10      
  max_name_length: 30

video:
  convert_path:     "./converted"
  delete_original:  true
  delete_old:
    enabled:        false
    days:           7
    check_interval: "1h"

  resolutions:
    low:  "640x360"   #resolution for Low quality video 
    med:  "1280x720"  #resolution for Medium quality video
    high: "1920x1080" #resolution for High quality video 

  bitrates:
    low:  "500k"      #BitRate value used in low conversion
    med:  "1500k"     #BitRate value used in medium conversion
    high: "3000k"     #BitRate value used in high conversion

  ffmpeg:
    threads: "1"
    preset:  "faster"    # ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow

  streaming:
    dash:        true
    hls:         false
    allow_embed: true

ui:
  users_file_path: "./users.yaml"
  template_dir:    "./ui/html"
  static_path:     "./static"
  favicon:         "./static/favicon.ico"

auth:
  upload_allowed_roles:   ["admin", "user"]
  view_allowed_roles:     ["admin", "user"]
  delete_allowed_roles:   ["admin"]
